INSTALL spatial;
INSTALL httpfs;
LOAD spatial;
LOAD httpfs;

DROP TABLE IF EXISTS overture_partitions;

CREATE TABLE overture_partitions (
    release VARCHAR,
    theme VARCHAR,
    type VARCHAR,
    partition_id VARCHAR,
    minx DOUBLE,
    miny DOUBLE,
    maxx DOUBLE,
    maxy DOUBLE,
    parquet_url VARCHAR
);

-- INSERT statements for intersecting STAC partitions are generated by
-- run_02_connect_overture.py.

DROP VIEW IF EXISTS overture_buildings;

-- The read_parquet call is generated with only the intersecting parquet files.
-- Filtering is duplicated by bbox so DuckDB can use Parquet row-group metadata
-- and avoid reading irrelevant data from the remote file.
